### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattiasghodsian** [mattiasghodsian/Minizo#1]
## in-progress
- [x] #2
- [x] #4 

## Coming
- [ ] more options for musicbrainz search

## Done
- [x] #3 
- [x] Determine a solution to release data already imported for Beets, ensuring that write operations do not encounter any issues.
    - Delete `library.db` in `/home/node/.config/beets/` ?!
    - Remove beets script and run it in execa using `beet` ?
- [x] Option to rename file for `artist - track.type` on meta write ? 
- [x] Create UI for new musicbrainz endpoints
    - [x]  Meta search
    - [x]  View selected release data and write to file
- [x] ~~read/write metadata to file (find a good package to use)~~
    - ~~`https://taglib.org/`    - `https://github.com/Zazama/node-id3`~~
- [x] Use beets.io to write meta to files
- [x] Add action to write data to file in musicbrainz search modal
- [x] Endpoint for retrieving file metadata to enable its display on the front-end manager view.
